version: '2'

services:
    bot:
        build: .
        image: knowbot
        expose:
            - "${PORT}"
        environment:
            - PORT
            - TOKEN
            - CLIENT_ID
            - CLIENT_SECRET
            - PAGE_TOKEN
            - VERIFY_TOKEN
            - BOT_PLATFORM
            - SOCIAL_SEARCH_API
            - MONGO_DB_URI
